spring.application.name=ai-resume-analyzer
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_resume_analyzer
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true